### PR TITLE
Proposal to use pre-commit for continuous integration

### PR DESCRIPTION
**Pull request by dachengx**
## What does the code in this PR do / what does it improve?

Use `pre-commit`'s continuous integration.

The advantage of `pre-commit` is that:

1. It runs automatically when you `git commit`.
2. You will not upload codes that are not aligned with some styles.

The codes are changed only in code style, the requirement of hooks.

Note: `black` will force you to use double quotes, it actually auto-format for you, so do not worry.

You will see no reviewdog complaining, and pre-commit will do almost all formatting for you, and it is very fast.

## Can you briefly describe how it works?

To setup pre-commit:

```
cd strax
pip install pre-commit
pre-commit install
```

Besides basic whitespace and large files check,
1. `black` will **auto-format** your code, mainly about indent and line-length, and make auto-commit if necessary.
2. `docformatter` will **auto-format** your docstring, following google convention, and make auto-commit if necessary.
3. `flake8` will **check** the code-style, but in a more lite way than `wemake-python-styleguide`.

So there will be two pre-commit checks, one check of **changed files** when you `git commit`, and one check of **all files** by pre-commit CI.

## Can you give a minimal working example (or illustrate with a figure)?

When you `git commit`, it will automatically `pre-commit run` for the **changed** files, so actually you would not always run it manually.

If you want to check all the files, run `pre-commit run --all-files`. If you want to check the difference between the current branch and `main`, run `pre-commit run --from-ref main --to-ref .`. If you want to remove the color from the output, add `--color never`.

`black` and `docformatter` will change your code, you still need to make a commit by yourself on the changed part.

For more information, please go to https://pre-commit.com/ and https://pre-commit.ci/.

_Please include the following if applicable:_
  - [x] _Update the docstring(s)_
  - [ ] _Update the documentation_
  - [x] _Tests to check the (new) code is working as desired._
  - [ ] _Does it solve one of the open issues on github?_

Inspired by https://github.com/XENONnT/straxen/issues/1192

### CODE REVIEW

**Comment by JelleAalbers** [comment]
Since @WenzDaniel  asked for my thoughts:
  * This is really something that you as maintainers should decide. I appreciate you asking for my input but this will affect your day-to-day much more than mine.
  * If I'd have to maintain code written by others, using an autoformatter as "spring cleaning" would be very tempting.
  * However, if you auto-reformat a big existing codebase by algorithm, you may not be clarifying things as much as hiding meaning that was carefully put in by the people that (hopefully) understood the code when they wrote it.
  *  This is why at least I haven't been keen on autoformatters, e.g. in our [contribution guidelines](https://github.com/AxFoundation/strax/blob/master/CONTRIBUTING.md#code-style). The Raymond Hettinger talk linked there, especially the first 10min, has an insightful discussion as well.
  * If you do do go for it, I would suggest using `.git-blame-ignore-revs` (e.g. https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html) to avoid obfuscating who changed when (and in what context).

**Comment by dachengx** [comment]
> Since @WenzDaniel asked for my thoughts:
> 
> * This is really something that you as maintainers should decide. I appreciate you asking for my input but this will affect your day-to-day much more than mine.
> * If I'd have to maintain code written by others, using an autoformatter as "spring cleaning" would be very tempting.
> * However, if you auto-reformat a big existing codebase by algorithm, you may not be clarifying things as much as hiding meaning that was carefully put in by the people that (hopefully) understood the code when they wrote it.
> * This is why at least I haven't been keen on autoformatters, e.g. in our [contribution guidelines](https://github.com/AxFoundation/strax/blob/master/CONTRIBUTING.md#code-style). The Raymond Hettinger talk linked there, especially the first 10min, has an insightful discussion as well.
> * If you do do go for it, I would suggest using `.git-blame-ignore-revs` (e.g. https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html) to avoid obfuscating who changed when (and in what context).

Thanks, I will try `.git-blame-ignore-revs`.

**Comment by dachengx** [comment]
I think I will merge with this PR, and update the existing PRs(will not be a large amount of work). Because if we merge other PRs, I will need to do another round of `git squash`, to make all changes by pre-commit combined, again, which is cumbersome.

**Review by JelleAalbers — APPROVED** [review]
Sounds good! We discussed in the meeting; hope it will work out well.

**Pull request merged**
