### PR TITLE
Increase the timing precision of progress bar

### PR DESCRIPTION
**Pull request by dachengx**
**What is the problem / what does the code in this PR do**

To solve https://github.com/AxFoundation/strax/pull/816

**Can you briefly describe how it works?**

**Can you give a minimal working example (or illustrate with a figure)?**

Please include the following if applicable:
  - Update the docstring(s)
  - Update the documentation
  - Tests to check the (new) code is working as desired.
  - Does it solve one of the open issues on github?

Please make sure that all automated tests have passed before asking for a review (you can save the PR as a draft otherwise).

### CODE REVIEW

**Review by yuema137 — APPROVED** [review]
@dachengx Thanks for this PR and thanks for catching this issue @zaitsev136
Looking at #816 and this PR, I agree that it's a better solution to use an independent attribute.  The `last_print_t` is an attribute provided by `tqdm` which is updated with `time.time` in `__iter__`. So when we do 
https://github.com/AxFoundation/strax/blob/a1e921fce2519db5e58ac710487a6690475f0438/strax/context.py#L1473 or
https://github.com/AxFoundation/strax/blob/a1e921fce2519db5e58ac710487a6690475f0438/strax/context.py#L1552
The `pbar.last_print_t` will be overwritten by `time.time`. As we don't want to touch the inner side of `tqdm` it's good to separate the high-resolution time calculation with a different one.

**Comment by dachengx** [comment]
Let's wait for @zaitsev136 's review.

**Comment by zaitsev136** [comment]
Looking good, thanks a lot for looking into this

**Comment by dachengx** [comment]
> Looking good, thanks a lot for looking into this

Will this PR solve the error you saw?

**Comment by zaitsev136** [comment]
yes, it will

**Pull request merged**
