### PR TITLE
Change Delimiter to -

### PR DESCRIPTION
**Pull request by tunnell**
Solves #69 of underscore degeneracy.

### CODE REVIEW

**Comment by tunnell** [comment]
Warning: merging this will break all currently processed data.  Do not merge until we start a new processing.  Ideally, we should tag a release without this *then* merge this for next release.

**Comment by tunnell** [comment]
@JelleAalbers can you do a release then we merge this?

**Comment by JelleAalbers** [comment]
Unfortunately this will also make all currently existing file-based data unreadable. Perhaps we should add some logic to temporarily try _-joining for building filenames too, if --joining fails?

**Comment by tunnell** [comment]
Mainly issue for test data.  People stick with current version.  I bumped S3 version so won't see old data.

**Comment by JelleAalbers** [comment]
We still have to update the test data

**Pull request merged**
