### PR TITLE
Add option to ignore errors in multirun loading

### PR DESCRIPTION
**Pull request by JoranAngevaare**
**What is the problem / what does the code in this PR do**
A simple PR that will simplify the lives of many analysts that try loading many runs with one stubborn one failing.

**Can you briefly describe how it works?**
Please see the test, I think it's quite self-explaining.

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Sounds like a sensible addition. Shall we included in todays release?

**Comment by JoranAngevaare** [comment]
I think it needs tests first so let's not include it

**Comment by WenzDaniel** [comment]
Do you want to included in the release today or tomorrow?

**Comment by JoranAngevaare** [comment]
no did not have time to test it yet

**Review by WenzDaniel — APPROVED** [review]
Looks good and is definitely useful.

**Pull request merged**
