### PR TITLE
Select max gaps from positive gaps

### PR DESCRIPTION
**Pull request by dachengx**
**What is the problem / what does the code in this PR do**

Fix: https://github.com/AxFoundation/strax/issues/707

The plugins in [straxen](https://github.com/XENONnT/straxen) might also need to be updated. 

**Can you briefly describe how it works?**

Select max gaps from positive gaps, the gaps are differences between endtime of hits and time of hits. 

Change
```
p['max_gap'] = max(p['max_gap'], t0 - peak_endtime)
```
to
```
p['max_gap'] = max(p['max_gap'], abs(t0 - peak_endtime))
```

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Hej Dacheng thanks for spotting this, but I think this points to a different issue. `p['max_gap']` should be by default zero. So `max(p['max_gap'], t0 - peak_endtime)` can only be `>= 0` is not it? Could it be that we have an overflow of the buffer?

**Review by WenzDaniel — APPROVED** [review]

**Comment by dachengx** [comment]
> Hej Dacheng thanks for spotting this, but I think this points to a different issue. `p['max_gap']` should be by default zero. So `max(p['max_gap'], t0 - peak_endtime)` can only be `>= 0` is not it? Could it be that we have an overflow of the buffer?
> 
> Okay I just noticed that I misunderstood your PR. You are absolutely right, there should be an absolute value as the next hit in a peak can be beyond the peak endtime as long as the this hit is within the max_gap range.

Hey @WenzDaniel . Yes, you are right. Also the default value of `p['max_gap']` is -1.

**Comment by dachengx** [comment]
> Hey @WenzDaniel . Yes, you are right. Also the default value of `p['max_gap']` is -1. 

I just realized that the default value of `p['max_gap']` is indeed 0. We may see some `p['max_gap'] == -1` because we set it to -1 when [split the peak](https://github.com/AxFoundation/strax/blob/28553a74e6d56fc1dbb33b6c0d7cd381b0afb0aa/strax/processing/peak_splitting.py#L161).

**Comment by dachengx** [comment]
Let me illustrate more here, only for reference: 

Before put into `find_peaks`, the hits are [sorted](https://github.com/XENONnT/straxen/blob/81a206bd14e300cb4f98f1396074c046f5875bcd/straxen/plugins/peaklets/peaklets.py#L181), but by `time` and `channel`. So there might be the case that the following peak starts before previous peak ends. Thus `t0 - peak_endtime` can be negative. 

image

In the figure, `time` is solid lines and `endtime` is dashed lines.

**Comment by dachengx** [comment]
I guess the `max_gap` is meant to track the results of `find_peaks` because the function looks into the difference of `endtime` and `time`. But to make further use of hits properties, we might need some other features which I will add them in another PR.

**Review by JoranAngevaare — APPROVED** [review]

**Comment by dachengx** [comment]
> You mean the following _hit_ hit right? "following _hit_ starts before previous _hit_ ends"

Yes. Sorry, that is a typo.

**Comment by dachengx** [comment]
Shall we update the lineage of plugins in straxen?

**Pull request merged**
