### PR TITLE
Remove NotImplementedError for multi_output in DownChunkingPlugin

### PR DESCRIPTION
**Pull request by HenningSE**
**What is the problem / what does the code in this PR do**
Right now it is not possible to have a DownChunkingPlugin with multiple outputs. I would like to add truth information handling in fuse and for that I need a second output in the PMTResponseAndDAQ plugin. 

**Can you briefly describe how it works?**
The PR just removes the `NotImplementedError`.

**Can you give a minimal working example (or illustrate with a figure)?**
It was necessary to change how the PMTResponseAndDAQ yields its results a bit but I found no problems running the fuse simulations with the implemented changes. The corresponding fuse PR can be found here: https://github.com/XENONnT/fuse/pull/99.

### CODE REVIEW

**Comment by dachengx** [comment]
There is some discussion about this. As a reference: https://github.com/AxFoundation/strax/pull/769#discussion_r1386797972

**Comment by dachengx** [comment]
Hey @HenningSE . Is this still needed?

**Comment by HenningSE** [comment]
If we go with the Truth plugins as they are right now in the PR: no.

**Comment by dachengx** [comment]
We are still able to reopen this later.

**Pull request closed without merging**
