### PR TITLE
Improve chunks splitting in `OverlapWindowPlugin`

### PR DESCRIPTION
**Pull request by dachengx**
**What is the problem / what does the code in this PR do**

https://github.com/AxFoundation/strax/blob/b35db0a2f27be2746fb30c18d8f7d4b9d9e7722b/strax/plugins/overlap_window_plugin.py#L52-L53 set `allow_early_split=False` to make sure that the chunks are initialized correctly https://github.com/AxFoundation/strax/blob/b35db0a2f27be2746fb30c18d8f7d4b9d9e7722b/strax/chunk.py#L76-L85. 

In real data, we will sometime encounter overlapping peaks when the rate is high, so `result.split` will raise the error. 

**Can you briefly describe how it works?**

The added codes search for splitting time `invalid_beyond` where no items happen in `provides`. 

**Can you give a minimal working example (or illustrate with a figure)?**

Please include the following if applicable:
  - Update the docstring(s)
  - Update the documentation
  - Tests to check the (new) code is working as desired.
  - Does it solve one of the open issues on github?

Please make sure that all automated tests have passed before asking for a review (you can save the PR as a draft otherwise).

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Hej Dacheng, I am not sure what the current status of this PR is. Should I have a look? In addition, since it is a change for something so fundamental I think we should add a test.

**Comment by dachengx** [comment]
> Hej Dacheng, I am not sure what the current status of this PR is. Should I have a look? In addition, since it is a change for something so fundamental I think we should add a test.

Hey Daniel. The codes are done. I will add a test. Sorry for making so many commits after marking the PR as ready.

**Comment by WenzDaniel** [comment]
Since it is such a low level change can you provide maybe a test example where the old code fails and the new code passes? This would not only make reviewing much easier, but also provides some safety for the future.

**Comment by dachengx** [comment]
@WenzDaniel Yes, I am trying to add that.

The current condition is like this:
1. the `sorted(x)` makes the result of `sorted_bounds` still disjoint even if the `disjoint=False` is argued https://github.com/AxFoundation/strax/blob/cb5664fc7cf4960fb10b47bdeca659a9d5dcfaec/strax/testutils.py#L36-L38.
2. so this makes us seldom(never) noticed that the `touching_window` is giving the wrong results even in the pytest action, .
3. https://github.com/AxFoundation/strax/pull/725 will be updated to not only raise errors when containers' `endtime`s are sorted, following @jmosbacher's great idea.
4. But the current `touching_window` will still not work when the things' `endtime`s are not sorted, in these cases, we need to use `split_by_containment`.

**Comment by dachengx** [comment]
This PR is actually related to https://github.com/AxFoundation/strax/issues/490

**Pull request closed without merging**
