### PR TITLE
Use int32 for peak dt, fix #397

### LINKED ISSUE #397: dt integer overflow
We should add some test that the dt field can be stored in the int16. We either need to change the int16->int32 for everything or need to come up with some other smart solution. Effectively we cannot have peaks > 7ms due to this.

### PR DESCRIPTION
**Pull request by jorana**
**What is the problem / what does the code in this PR do**
Fix issue #397 , this way, we could create much much longer waveforms to never run into such issues again.

**Can you briefly describe how it works?**
Use a signed int for the dt field in peaks as they may well get very long

**What is needed on the straxen-side**
Full reprocessing of everything with `peak_interval_dtype` by incrementing the version of the affected plugins.

**Have you tested this on the known culprit?**
Not yet, let's first discuss if we want to go down this road

**Why not uint16?**
Could also do that. I actually think np.int32 might be even better so as to stay well away from the boundary, also, the biggest cost (i.e. reprocessing) stays the same for either option.

**Why not cap the WF to a max duration**
See #397

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Hmm and raw_records? It is also an interval dtype which would be affected.

**Comment by darrylmasson** [comment]
I think there are pros and cons to both `uint16` and `int32`. `int32` is future-proof, because we will never have peaks with duration 2s, however this would a) invalidate all currently stored raw_records, and b) require a corresponding patch in redax. We've already changed the lowest-level dtype once (#237), and right now doesn't seem like the best time to do it again. `uint16` only buys us a factor of 2, but this doesn't invalidate raw_records because the digitizers can't store enough data to be affected by this, so we wouldn't have to up-convert any of the massive data.

**Comment by darrylmasson** [comment]
Also, for all records-type data, this value is either 2 or 10, because there is no down-sampling at the readout level.

**Comment by jorana** [comment]
@darrylmasson @WenzDaniel , you are both right, I was a bit too quick. I've changed it now only for peaks, which should only require a version bump of peaklets and a change of the Merged S2 dtype.

Reprocessing will happen sooner or later, I think better do it within next three weeks. Might want to do this when peak-classification is changed for example.

**Review by darrylmasson — APPROVED** [review]

**Review by WenzDaniel — APPROVED** [review]
No comments.

**Comment by jorana** [comment]
Okay, then I will keep this PR in the fridge until the opportune moment presents itself

**Comment by jorana** [comment]
For bookkeeping, see https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:analysis:commissioning:telecons:20210126#updates_on_daq

**Pull request merged**
