### PR TITLE
Saturation correction at peak level

### PR DESCRIPTION
**Pull request by zhut19**
Adding saturation correction function that 
  - Reads in both peak or peaklet and records, correlate records with saturated peaks.
  - Build a pulse model (currently using sum wf of non-saturated channels)
  - Correct records data
  - Redo sum_waveform on selected peak or peaklets
  - Return the peak indices which were corrected.

### CODE REVIEW

**Comment by JelleAalbers** [comment]
Looks nice Tianyu! Is this is ready for review? Do you (or ACs) have a suggestion for a reviewer?

**Comment by zhut19** [comment]
Thanks, Jelle! I can write to the ACs if this is ready for review and for reviewer suggestions.

**Comment by tunnell** [comment]
Maybe @reallsx?  I sort of hope he learns about this stuff.

**Comment by feigaodm** [comment]
It would be good if someone who wants to learn about it to look at it, and check the technical details of implementation. I would then tag @reallsx and Mike (didn't find his id).

**Comment by zhut19** [comment]
Migrated to https://github.com/XENONnT/straxen/pull/244

**Pull request closed without merging**
