### PR TITLE
Fix mongo path conflicts

### PR DESCRIPTION
**Pull request by jmosbacher**
**What is the problem / what does the code in this PR do**
This should fix issue #324

**Can you briefly describe how it works?**
After collecting all the projections, the most specific projection for each field is chosen. e.g if both "tags" and "tags.name" are requested, only "tags.name" will actually go into the mongo query. This will reproduce the old mongodb behavior.

A new test for this should be added. Hope to have time to do this soon.

### CODE REVIEW

**Comment by jorana** [comment]
@jmosbacher , thanks for the quick fix! I'm merging it already. I just tested it and it seems to work. Perhaps we can keep issue #324 open and mention the tests there.

**Comment by jorana** [comment]
Looking at this a little more closely, it looks like a straxen-issue rather than a strax issue. It seems that https://github.com/XENONnT/straxen/pull/241 would be a viable solution right? At least, if I quickly run that on my laptop it seems to solve the issue.

**Comment by jmosbacher** [comment]
Sorry I just realized my quick fix doesnt work as intended for the edge case when two fields have names that start the same way. So if you request eg both date and datetime for example (not real fields but could be) then you would only get datetime. I added another commit, this is shorter and should work in all cases (i think).

**Comment by jmosbacher** [comment]
> Looking at this a little more closely, it looks like a straxen-issue rather than a strax issue. It seems that [XENONnT/straxen#241](https://github.com/XENONnT/straxen/pull/241) would be a viable solution right? At least, if I quickly run that on my laptop it seems to solve the issue.

@jorana Yes, I think you are right. Good catch! I didnt think it through, just chased down the source of the error. But I guess a non mongo frontend could support fields and sub-fields in parallel so no reason to limit ourselves here.

**Comment by jorana** [comment]
@ jmosbacher , would we still want to add this to strax or otherwise add a comment with a reference to this PR/issue such that it's easier to debug if others run into it?

**Comment by jmosbacher** [comment]
@jorana Good question. I think this pull request is now redundent so definitely no need to merge it. I like the idea of a comment. In any case I am closing this pull request.

**Pull request closed without merging**
